---

# Version 1.4.0

- hosts: "localhost"
  vars:
    proxmox_api_host: "pvehost1"
    proxmox_api_user: "root@pam"
    proxmox_api_password: "SuperSecretPassword"
    proxmox_api_port: "8006"
    boot_time: 180
    vm_list:
      - vm_name: myShinyVM1
      - vm_name: myShinyVM2
        snapshot: true
        reboot_if_required: true

  tasks:

  - name: Logon to Proxmox Server
    ansible.builtin.uri:
      method: POST
      validate_certs: false
      return_content: true
      url: "https://{{ proxmox_api_host }}:8006/api2/json/access/ticket"
      body_format: json
      body:
        username: "{{ proxmox_api_user }}"
        password: "{{ proxmox_api_password }}"
    register: proxmox_session
    become: false

  - name: parse cookie data
    ansible.builtin.set_fact:
      proxmox_api_cookie:
        Cookie: "PVEAuthCookie={{ proxmox_session.json.data.ticket }}"
        CSRFPreventionToken: "{{ proxmox_session.json.data.CSRFPreventionToken }}"
    no_log: true

  - name: get information about all vms in the cluster
    ansible.builtin.uri:
      method: GET
      validate_certs: false
      url: "https://{{ proxmox_api_host }}:8006/api2/json/cluster/resources?type=vm"
      headers: "{{ proxmox_api_cookie }}"
    register: proxmox_cluster_information

  - name: Patch VM
    ansible.builtin.include_tasks: patch_vm.yml
    loop: "{{ vm_list }}"
